### PR TITLE
SC and TMDB

### PR DESCRIPTION
**Pull request by eckomega**
Add SC as a site and TMDB search link.

### CODE REVIEW

**Comment by kannibalox** [comment]
I appreciate the effort, but SP has already been added from https://github.com/kannibalox/IMDb-Scout/commit/8739fa765561f2e2a2cc188f2e3b6d0d9fec3698, and if you want to submit PRs, please submit them as changes against the existing [IMDb_Scout.user.js](https://github.com/kannibalox/IMDb-Scout/blob/master/IMDb_Scout.user.js) and not as a whole new file.

**Comment by eckomega** [comment]
> 
> 
> I appreciate the effort, but SP has already been added from [8739fa7](https://github.com/kannibalox/IMDb-Scout/commit/8739fa765561f2e2a2cc188f2e3b6d0d9fec3698), and if you want to submit PRs, please submit them as changes against the existing [IMDb_Scout.user.js](https://github.com/kannibalox/IMDb-Scout/blob/master/IMDb_Scout.user.js) and not as a whole new file.

I use scout daily but am new to github. I tried to add SC to this one but I'm not sure why those lines weren't included.

How do I go about submitting the changes to the existing IMDb_Scout.user.js. I wanted to do this, but am confused on how  :-/

**Comment by kannibalox** [comment]
You had it pretty much correct, but you made a whole new file called `IMDb Scout.user.js`, when there should have only been a small change to the `IMDb_Scout.user.js` file (note the underscore). Regardless, both of your changes have been merged into the script, just under different commits.

**Comment by kannibalox** [comment]
> The only way I was able to create them was by making the changes to the script, uploading it to my fork, then creating the pull request across forks.

That's the right way to do it, but when you made your changes, your changes ended up in a completely new file named `IMDb Scout.user.js` instead of just making changes to the existing `IMDb_Scout.user.js` , I'm not sure of any other way to phrase that. If you didn't manually change the file name, you might want to check that whatever editor you're using isn't doing in the background.

Regardless, both of the changes you submitted are now part of the script (I put the changes in manually) which is why I closed the PR.

**Pull request closed without merging**
